/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/xxx

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temp;
  float humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "ArduinoIoTCloud.h"
#include "Arduino_ConnectionHandler.h"

const char THING_ID[] = "0cb9296e-db24-488f-acab-fb0bf99ae9e7";  // Thing ID

// Arduino Cloud OAuth 認證資訊
const char DEVICE_LOGIN_NAME[]  = "0cb9296e-db24-488f-acab-fb0bf99ae9e7";  // Client ID
const char DEVICE_KEY[]          = "OXJfX9lit@9?Ej?YeIk6e5yNU";  // Client Secret

const char SSID[]     = "Chou";    // Network SSID (name)
const char PASS[]     = "0935963000";    // Network password (use for WPA, or use as key for WEP)

// Arduino Cloud 變數定義（必須與 Cloud 中的變數名稱和類型一致）
// 注意：變數名稱必須與 Cloud 中的 Declaration 完全一致（包括大小寫）
float temp;
float humidity;
bool LED_switch;  // 如果 Cloud 中 Declaration 是 lED_switch，請改為 bool lED_switch;

// LED 開關改變時的回調函數
void onLEDSwitchChange();

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(LED_switch, READWRITE, ON_CHANGE, onLEDSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

